apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bridge-2

resources:
  - ../../base
  - service-account.yaml

configMapGenerator:
  - name: bridge-config
    behavior: merge
    envs:
      - configmap/bridge-config.env
  - name: bridge-access-lists
    behavior: replace
    files:
      - configmap/allowance_list.txt
      - configmap/block_list.txt

patches:
  - path: deploy-with-secret-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: "patches=with-secret-manager"
