apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base
  - service-account.yaml

configMapGenerator:
  - name: nftparser-config
    behavior: merge
    envs:
      - configmap/nftparser-config.env

patches:
  - path: deploy-with-secret-patch.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: "patches=with-secret-manager"
